def download_template(url):
    download_command = [
        "yt-dlp",
        ### General Options:
        "--help",
        "--version",
        "--update",
        "--update-to", "[CHANNEL]@[TAG]",
        "--ignore-errors",
        "--no-abort-on-error",
        "--abort-on-error",
        "--dump-user-agent",
        "--list-extractors",
        "--extractor-descriptions",
        "--use-extractors","NAMES"
        "--default-search","PREFIX",
        "--ignore-config",
        "--no-config-locations",
        "--config-locations","PATH",
        "--flat-playlist",
        "--no-flat-playlist",
        "--live-from-strart",
        "--no-live-from-strart",
        "--wait-for-video","MIN","[-MAX]",
        "--no-wait-for-video",
        "--mark-watched",
        "--no-mark-watched",
        "--color","[STREAM: ]","POLICY",
        "--compat-options","OPTS",
        "--alias","ALISES","OPTIONS",
        ### Network Options:
        "--proxy", "URL",
        "--socket-timeout","SECONDS",
        "--source-address","IP",
        "--force-ipv4",
        "--force-ipv6",
        "--enable-file-urls",
        ### Geo-restriction:
        "--geo-verification-proxy","URL",
        "--xff","VALUE",
        ### Video Selection:
        "--playlist-items","ITEM_SPEC",
        "--min-filesize","SIZE",
        "--max-filesize","SIZE",
        "--date","DATE",
        "--datebefore","DATE",
        "--dateafter","DATE",
        "--match-filters","FILTER",
        "--no-match-filters",
        "--break-match-filters","FILTER",
        "--no-break-match-filters",
        "--no-playlist",
        "--yes-playlist",
        "--age-limit","YEARS",
        "--download-archive","FILE",
        "--no-download-archive",
        "--max-downloads","NUMBER",
        "--break-on-existing",
        "--break-per-input",
        "--no-break-per-input",
        "--skip-playlist-after-errors","N",        
        ### Download Options:
        "--concurrent-fragments","N",
        "--limit-rate","10.0M",
        "--throttled-rate","100K",
        "--retries","RETRIES",
        "--file-access-retries","RETRIES",
        "--fragment-retries","RETRIES",
        "--retry-sleep","[TYPE:]","EXPR",
        "--skip-unavailable-fragments",
        "--abort-on-unavailable-fragments",
        "--keep-fragments",
        "--no-keep-fragments",
        "--buffer-size","SIZE",
        "--resize-buffer",
        "--no-resize-buffer",
        "--http-chunk-size","SIZE",
        "--playlist-random",
        "--lazy-playlist",
        "--no-lazy-playlist",
        "--xattr-set-filesize",
        "--hls-use-mpegts",
        "--no-hls-use-mpegts",
        "--download-sections","REGEX",
        "--downloader","[PROTO:]NAME",
        "--downloader-args","NAME:ARGS",
        ### Filesystem Options:
        "--batch-file","FILE",
        "--no-batch-file",
        "--paths","[TYPES:]PATH",
        "--output","./Audio/%(title)s.%(ext)s",
        "--output-na-placeholder","TEXT",
        "--restrict-filenames",
        "--no-restrict-filenames",
        "--windows-filenames",
        "--no-windows-filenames",
        #"--trim-filenames", "32", # This option poofs for admin perms.
        "--no-overwrites",
        "--force-overwrites",
        "--no-force-overwrites",
        "--continue",
        "--no-continue",
        "--part",
        "--no-part",
        "--mtime",
        "--no-mtime",
        "--write-description",
        "--no-write-description",
        "--write-info-json",
        "--no-write-info-json",
        "--write-playlist-metafiles",
        "--no-write-playlist-metafiles",
        "--clean-info-json",
        "--no-clean-info-json",
        "--write-comments",
        "--no-write-comments",
        "--load-info-json","FILE",
        "--cookies","FILE",
        "--no-cookies",
        "--cookies-from-browser","BROWSER",
        "--no-cookies-from-browser",
        "--cache-dir","DIR",
        "--no-cache-dir",
        "--rm-cache-dir",
        ### Thumbnail Options:        
        "--write-thumbnail",
        "--no-write-thumbnail",
        "--write-all-thumbnails",
        "--list-thumbnails",
        ### Internet Shortcut Options:
        "--write-link",
        "--write-url-link",
        "--write-webloc-link",
        "--write-desktop-link",        
        ### Verbosity and Simulation Options:
        "--quiet",
        "--no-quiet",
        "--no-warnings",
        "--simulate",
        "--no-simulate",
        "--ignore-no-formats-error",
        "--no-ignore-no-formats-error",
        "--skip-download",
        "--print","[WHEN:]TEMPLATE",        
        "--print-to-file","[WHEN:]TEMPLATE FILE",
        "--dump-json",
        "--dump-single-json",
        "--force-write-archive",
        "--newline",
        "--no-progress",
        "--progress",
        "--console-title",
        "--progress-template","[TYPES:]TEMPLATE",
        "--verbose",
        "--dump-pages",
        "--write-pages",
        "--print-traffic",        
        ### Workarounds:
        "--encoding","ENCODING",
        "--legacy-server-connect",
        "--no-check-certificates",
        "--prefer-insecure",
        "--add-headers","FIELD:VALUE",
        "--bidi-workaround",
        "--sleep-requests","SECONDS",
        "--sleep-interval","SECONDS",
        "--max-sleep-interval","SECONDS",
        "--sleep-subtitles","SECONDS",
        ### Video Format Options:
        "--format","bestaudio", # mp3/bestaudio/best
        "--format-sort","SORTORDER",
        "--format-sort-force",
        "--no-format-sort-force",
        "--video-multistreams",
        "--no-video-multistreams",
        "--audio-multistreams",
        "--no-audio-multistreams",
        "--prefer-free-formats",
        "--no-prefer-free-formats",
        "--check-formats",
        "--check-all-formats",
        "--no-check-formats",
        "--list-formats",
        "--merge-output-format","FORMAT",
        ### Subtitle Options:
        "--write-subs",
        "--no-write-subs",
        "--write-auto-subs",
        "--no-write-auto-subs",
        "--list-subs",
        "--sub-format","FORMAT",
        "--sub-langs","LANGS",
        ### Authentication Options:
        "--username","USERNAME",
        "--password","PASSWORD",
        "--twofactor","TWOFACTOR",
        "--netrc",
        "--netrc-location","PATH",
        "--netrc-cmd","NETRC_CMD",
        "--video-password","PASSWORD",
        "--ap-mso","MSO",
        "--ap-username","USERNAME",
        "--ap-password","PASSWORD",
        "--ap-list-mso",
        "--client-certificate","CERTFILE",
        "--client-certificate-key","KEYFILE",
        "--client-certificate-password","PASSWORD",
        ### Post-Processing Options:
        "--extract-audio",
        "--audio-format","mp3",
        "--audio-quality","320k",
        "--remux-video","FORMAT",
        "--recode-video","FORMAT",
        "--postprocessor-args","NAME:ARGS",
        "--keep-video",
        "--no-keep-video",
        "--post-overwrites",
        "--no-post-overwrites",
        "--embed-subs",
        "--no-embed-subs",
        "--embed-thumbnail",
        "--no-embed-thumbnail",
        "--embed-metadata",
        "--no-embed-metadata",
        "--embed-chapters",
        "--no-embed-chapters",
        "--embed-info-json",
        "--no-embed-info-json",
        "--parse-metadata","[WHEN:]FROM:TO",
        "--replace-in-metadata","[WHEN:]FIELDS REGEX REPLACE",
        "--xattrs",
        "--concat-playlist","POLICY",
        "--fixup","POLICY",
        "--ffmpeg-location","PATH",
        "--exec","[WHEN:]CMD",
        "--no-exec",
        "--convert-subs","FORMAT",
        "--split-chapters",
        "--no-split-chapters",
        "--remove-chapters","REGEX",
        "--no-remove-chapters"
        "--force-keyframes-at-cuts",
        "--no-force-keyframes-at-cuts",
        "--use-postprocessor","NAME[:ARGS]",        
        ### SponsorBlock Options:
        "--sponsorblock-mark","CATS",
        "--sponsorblock-remove","CATS",
        "--sponsorblock-chapter-title","TEMPLATE",
        "--no-sponsorblock",
        "--sponsorblock-api","URL",
        ### Extractor Options:
        "--extractor-retries","RETRIES",
        "--allow-dynamic-mpd",
        "--ignore-dynamic-mpd",
        "--hls-split-discontinuity",
        "--no-hls-split-discontinuity",
        "--extractor-args","IE_KEY:ARGS",
        url
    ]    
    #subprocess.run(download_command)
    print('Downloaded.')

def main(url):
    print('')

# main if ran as script.
if __name__ == "__main__":
    main()
